### ISSUE TITLE
Review Zephyr-specific patches

### ISSUE THREAD

**Issue by stephanosio** [stephanosio/zephyr-crosstool-ng#15]
The version of crosstool-ng used in this repository includes newer toolchain components:

* binutils 2.34 (sdk-ng uses 2.32)
* newlib 3.3.0 (sdk-ng uses 3.1.0.20181231)

Review and assess whether the following patches are still relevant for these newer component versions:

### binutils (2.32 -> 2.34)

- [x] 0001-GAS-Arm-PR24559-Fix-pseudo-load-operations-for-Armv8.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/8fe9a076adf308ec813246a96f915c5ab5b6a75f))
- [x] 0001-RISC-V-Compress-3-operand-beq-bne-against-x0.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/ca0bc1509849a3871e99fdf48705b93f18d5fa7b))
- [x] 0002-RISC-V-Fix-linker-crash-in-section-symbol-check.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/a9f5a5517fb7df640f0fcd4cb0f9961818b6505b))
- [x] 0003-RISC-V-Relax-tail-j-to-c.j-for-RV64.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/ae2b14c73cd42b067e9687219155ed044210f0c1))
- [x] 0004-RISC-V-Don-t-check-ABI-flags-if-no-code-section.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/87f98bacb76001157d5a26555a41738ac3841a56))
- [x] 0005-RISC-V-Enable-32-bit-linux-gdb-core-file-support.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/79b8e8ab453619cb0262e1ad18447d918a605073))
- [x] 0006-RISC-V-Fix-lui-argument-parsing.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/4288405d5ec2c68c7e9d8d68a090c6c9ff3825d1))
- [x] 0007-RISC-V-Enable-lui-relaxation-for-CODE-and-MERGE-sect.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/04b865dc2ede2b8ca8c60f0487a179eb97895fee))
- [x] 0008-RISC-V-Make-objdump-disassembly-work-right-for-binar.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/d7560e2df501c7da1b0e4e64116dd52fe5715a96))
- [x] 0009-Kito-s-5-part-patch-set-to-improve-.insn-support.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/98602811d838077269e361e9d807fe530c780011))
- [x] 0010-RISC-V-Fix-minor-issues-with-FP-csr-instructions.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/c0d6f62fcec939ab896e4839f6aa14ebfcd43565))
- [x] 0011-RISC-V-Fix-lui-relax-failure-with-relro.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/0f52d45acd6c54aa47082778ffcbafddd423a5b4))
- [x] 0012-RISC-V-Fix-lui-relaxation-issue-with-code-at-address.patch ([patch is in](https://github.com/bminor/binutils-gdb/commit/080a488354d63fec9791a26fadd15e0c5246983d))

### newlib 3.3.0 (3.1.0.20181231 -> 3.3.0)

- [x] 0001-work-arc-issue-with-nsim-and-fcntrl.patch (not upstreamed; mergeable)
- [x] 0002-Recognize-x86_64-zephyr.patch (not upstreamed; mergeable)
- [x] 0003-Support-building-for-32-bit-under-x86_64.patch (not upstreamed; conflict resolved)

### NOTE

* `patches/gdb/8.1.1` and `patches/gdb/8.2.1` are no longer relevant (@galak @dcpleung could you confirm this?)
* ~`patches/newlib/git-b06f1b57` is no longer relevant (@galak @dcpleung this as well)~ this is required since Xtensa targets use them

**Comment by dcpleung** [comment]
`patches/gdb/8.1.1` and `patches/gdb/8.2.1` are no needed anymore. No configs are using GDB 8.1 or 8.2 by simple grep.

`patches/newlib/git-b06f1b57` is still needed for the configs requiring `newlib-xtensa.git`. The branch `xtensa` in that repo has SHA `b06f1b57`. AFAIK, there has been no update to Xtensa support on newlib, and we are stuck with that (of newlib 2.2).

**Comment by stephanosio** [comment]
> `patches/newlib/git-b06f1b57` is still needed for the configs requiring `newlib-xtensa.git`. The branch `xtensa` in that repo has SHA `b06f1b57`. AFAIK, there has been no update to Xtensa support on newlib, and we are stuck with that (of newlib 2.2).

@dcpleung I can see that is indeed the case. Thanks for checking.

https://github.com/zephyrproject-rtos/sdk-ng/blob/55b005b6a00b64b5fa38cbbf29ec42fbb1ad7844/configs/xtensa_intel_apl_adsp.config#L16-L17

https://github.com/jcmvbkbc/newlib-xtensa/commits/xtensa
