### ISSUE TITLE
Integrate Xtensa HAL build process

### ISSUE THREAD

**Issue by stephanosio** [stephanosio/zephyr-crosstool-ng#2]
Integrate Xtensa HAL build process

Note that the current sdk-ng way of handling this cannot work for Canadian cross builds

**Comment by dcpleung** [comment]
FYI, building Xtensa HAL in SDK is no longer needed as the HAL is being built at build time. Here is the PR to remove the code to build HAL: https://github.com/zephyrproject-rtos/sdk-ng/pull/193

**Comment by stephanosio** [comment]
> FYI, building Xtensa HAL in SDK is no longer needed as the HAL is being built at build time. Here is the PR to remove the code to build HAL: [zephyrproject-rtos/sdk-ng#193](https://github.com/zephyrproject-rtos/sdk-ng/pull/193)

@dcpleung That's great! Thanks for confirming.
